<?php
declare(strict_types=1);

// HubspotEvents SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

HubspotEventsUtility::setRegistrar(function (HubspotEventsUtility $u): void {
    $u->clean = [HubspotEventsClean::class, 'call'];
    $u->done = [HubspotEventsDone::class, 'call'];
    $u->make_error = [HubspotEventsMakeError::class, 'call'];
    $u->feature_add = [HubspotEventsFeatureAdd::class, 'call'];
    $u->feature_hook = [HubspotEventsFeatureHook::class, 'call'];
    $u->feature_init = [HubspotEventsFeatureInit::class, 'call'];
    $u->fetcher = [HubspotEventsFetcher::class, 'call'];
    $u->make_fetch_def = [HubspotEventsMakeFetchDef::class, 'call'];
    $u->make_context = [HubspotEventsMakeContext::class, 'call'];
    $u->make_options = [HubspotEventsMakeOptions::class, 'call'];
    $u->make_request = [HubspotEventsMakeRequest::class, 'call'];
    $u->make_response = [HubspotEventsMakeResponse::class, 'call'];
    $u->make_result = [HubspotEventsMakeResult::class, 'call'];
    $u->make_point = [HubspotEventsMakePoint::class, 'call'];
    $u->make_spec = [HubspotEventsMakeSpec::class, 'call'];
    $u->make_url = [HubspotEventsMakeUrl::class, 'call'];
    $u->param = [HubspotEventsParam::class, 'call'];
    $u->prepare_auth = [HubspotEventsPrepareAuth::class, 'call'];
    $u->prepare_body = [HubspotEventsPrepareBody::class, 'call'];
    $u->prepare_headers = [HubspotEventsPrepareHeaders::class, 'call'];
    $u->prepare_method = [HubspotEventsPrepareMethod::class, 'call'];
    $u->prepare_params = [HubspotEventsPrepareParams::class, 'call'];
    $u->prepare_path = [HubspotEventsPreparePath::class, 'call'];
    $u->prepare_query = [HubspotEventsPrepareQuery::class, 'call'];
    $u->graphql_body = [HubspotEventsGraphql::class, 'body'];
    $u->graphql_errors = [HubspotEventsGraphql::class, 'errors'];
    $u->result_basic = [HubspotEventsResultBasic::class, 'call'];
    $u->result_body = [HubspotEventsResultBody::class, 'call'];
    $u->result_headers = [HubspotEventsResultHeaders::class, 'call'];
    $u->transform_request = [HubspotEventsTransformRequest::class, 'call'];
    $u->transform_response = [HubspotEventsTransformResponse::class, 'call'];
});
